### PR TITLE
Fix/103 add support for next forecast by remark

### LINKED ISSUE #103: Add support for Canadian TAF next forecast remark
It would be great if the remark parser could handle the canadian `NXT FCST BY` remark which indicates when the next TAF will be issued.

E.g.

```
TAF CYVR 152340Z 1600/1706 29015KT P6SM FEW015
BECMG 1603/1605 32010KT
FM160800 32008KT P6SM SCT008
TEMPO 1608/1617 BKN008
FM161700 28010KT P6SM FEW012
FM162200 28010KT P6SM SKC RMK NXT FCST BY 160300Z
```

### PR DESCRIPTION
**Pull request by fkrauthan**
Added support to parse the `NXT FCST BY ` remark often found in canadian TAFs. This effectively fixes #103

### CODE REVIEW

File: src/command/remark/NextForecastByCommand.ts [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+    return this.#regex.test(code);
+  }
+
+  execute(code: string, remark: Remark[]): [string, Remark[]] {
+    const matches = code.match(this.#regex);
+
+    if (!matches) throw new UnexpectedParseError("Match not found");
+
+    const day = +matches[1];
+    const hour = matches[2];
```
Comment (aeharding) [inline src/command/remark/NextForecastByCommand.ts:33]: Nit: consistently `+` here or at `remark.push` for day/hour/minute

File: src/dates/metar.ts [hunk 2]
```diff
@@ -8,6 +9,21 @@ export interface IMetarDated extends IMetar {
 export function metarDatesHydrator(report: IMetar, date: Date): IMetarDated {
   return {
     ...report,
+    remarks: report.remarks.map((remark) => {
```
Comment (aeharding) [inline src/dates/metar.ts:12]: Do real METARs in Canada have NXT FCST BY?

If not, it is ok to not hydrate here since it should never happen (if it does, lets add a test case for coverage)

File: src/command/remark/NextForecastByCommand.ts [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+
+export interface INextForecastByRemark extends IBaseRemark {
+  type: RemarkType.NextForecastBy;
+
+  day: number;
+  hour: number;
+  minute: number;
+}
+
+export interface INextForecastByRemarkDated extends INextForecastByRemark {
```
Comment (aeharding) [inline src/command/remark/NextForecastByCommand.ts:14]: It might be too much work, but it would be cool if this type could automatically be provided for type guarding on `RemarkType.NextForecastBy` if using dated taf or forecast parsing. Kind of like `TAFTrendDated`, maybe create and override with a `DatedRemark` or something like that?

File: src/dates/taf.ts [hunk 4]
```diff
@@ -93,6 +94,21 @@ export function tafDatesHydrator(report: ITAF, date: Date): ITAFDated {
...
+              return {
+                ...remark,
+                date: determineReportDate(
+                  issued,
+                  remark.day,
+                  remark.hour,
+                  remark.minute,
+                ),
+              };
+            } else {
```
Comment (aeharding) [inline src/dates/taf.ts:108]: Nit: not necessary else statement

**Review by aeharding — CHANGES_REQUESTED** [review]
Looks good, mostly nits, I'm curious if you could try to get a `RemarkDated` type made for smarter types!

File: src/command/remark/NextForecastByCommand.ts (hunk 1 above)
Comment (fkrauthan) [reply src/command/remark/NextForecastByCommand.ts:33]: I actually did this on purpose here as for the `description` string I want single digit day (e.g. `1` rather `01` while I do want the double digit hour and minute. Or should I add the `+` to both description and the `push` in this case?

Comment (aeharding) [reply src/command/remark/NextForecastByCommand.ts:33]: I see! Feel free to leave it as is then.

File: src/dates/metar.ts (hunk 2 above)
Comment (fkrauthan) [reply src/dates/metar.ts:12]: No its only something TAF has I added it for completion. Gonna remove it.

File: src/dates/taf.ts (hunk 4 above)
Comment (fkrauthan) [reply src/dates/taf.ts:108]: Changed

File: src/command/remark/NextForecastByCommand.ts (hunk 3 above)
Comment (fkrauthan) [reply src/command/remark/NextForecastByCommand.ts:14]: I've implement that now. Take a look if that works for you.

File: src/command/remark.ts [hunk 5]
```diff
@@ -308,9 +316,13 @@ export enum RemarkType {
...
   SunshineDuration = "SunshineDuration",
   WaterEquivalentSnow = "WaterEquivalentSnow",
+
+  // Canada commands below
+  NextForecastBy = "NextForecastBy",
 }
 
-export type Remark =
+// Remark types that are not date based
+export type RemarkBase =
```
Comment (aeharding) [inline src/command/remark.ts:325]: Remove export

File: src/command/remark.ts [hunk 6]
```diff
@@ -354,3 +365,13 @@ export type Remark =
...
+
+export type RemarkDated =
+  | RemarkBase
+  // Canadian commands below
+  | INextForecastByRemarkDated;
+
+export type Remark =
+  | RemarkBase
+  // Canadian commands below
+  | INextForecastByRemark;
```
Comment (aeharding) [inline src/command/remark.ts:377]: These also need to be exported in index.ts:

INextForecastByRemarkDated
INextForecastByRemark
RemarkDated

(no need to export RemarkBase, it's internal)

**Review by aeharding — COMMENTED** [review]
The RemarkDated works great, thanks!

File: src/command/remark.ts (hunk 6 above)
Comment (fkrauthan) [reply src/command/remark.ts:377]: done

File: src/command/remark.ts (hunk 5 above)
Comment (fkrauthan) [reply src/command/remark.ts]: I was thinking of not adding `export` when doing this but I guess I forgot to actually not add it...

**Review by aeharding — APPROVED** [review]

**Comment by aeharding** [comment]
Thanks!
